# .github/workflows/build.yml

name: Java Build and Artifact Upload

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean package

      - name: Upload JAR/WAR as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-artifact
          path: target/*.jar  # Change to `target/*.war` if you are building a WAR

